import { Mic2, FileText, Languages, BarChart3, Radio, Zap, Star, Crown } from "lucide-react";
import React from "react";

export const SERVICES = [
  {
    icon: <Mic2 size={22} />,
    title: "AI Mock Interviews",
    tag: "Core Feature",
    tagColor: "text-amber-500 bg-amber-500/10 border-amber-500/20",
    description: "Practice real interviews with an AI interviewer tailored to your exact job role and experience level. Get asked progressive questions — from DSA to system design to behavioral — and receive instant feedback after every answer.",
    highlights: [
      "10 questions per session, progressively harder",
      "Tailored to 20+ CSE roles and domains",
      "Real-time AI feedback on every answer",
      "Voice and chat mode supported",
      "Session history and score tracking",
    ],
    free: "5 sessions/month",
    pro: "Unlimited sessions",
    color: "hover:border-amber-500/40",
    glow: "hover:shadow-[0_0_30px_rgba(251,191,36,0.1)]",
    iconBg: "bg-amber-500/10 text-amber-500",
  },
  {
    icon: <FileText size={22} />,
    title: "AI CV Builder",
    tag: "Career Tool",
    tagColor: "text-emerald-500 bg-emerald-500/10 border-emerald-500/20",
    description: "Stop staring at a blank page. Fill in your experience, projects, and skills — our AI rewrites everything into a polished, professional CV with impact-driven language that gets noticed by recruiters.",
    highlights: [
      "4-step guided input flow",
      "AI rewrites your experience with impact language",
      "Structured JSON output for clean formatting",
      "Downloadable PDF export",
      "Tailored to your target role",
    ],
    free: "2 CVs/month",
    pro: "Unlimited CVs",
    color: "hover:border-emerald-500/40",
    glow: "hover:shadow-[0_0_30px_rgba(52,211,153,0.1)]",
    iconBg: "bg-emerald-500/10 text-emerald-500",
  },
  {
    icon: <Languages size={22} />,
    title: "JP-Sensei Japanese Learning",
    tag: "Language",
    tagColor: "text-violet-500 bg-violet-500/10 border-violet-500/20",
    description: "A structured, efficient roadmap to Japanese fluency — built specifically for CSE students and developers. From Hiragana to JLPT N1, every topic is prioritized, timed, and explained with actionable tips.",
    highlights: [
      "4-phase learning roadmap (Foundation → Mastery)",
      "20+ topics with time estimates and expert tips",
      "Daily study routine with 6 structured sessions",
      "8 curated resources (Anki, Genki, WaniKani etc.)",
      "Track progress by checking off completed topics",
    ],
    free: "Full access",
    pro: "Full access + AI conversation practice",
    color: "hover:border-violet-500/40",
    glow: "hover:shadow-[0_0_30px_rgba(167,139,250,0.1)]",
    iconBg: "bg-violet-500/10 text-violet-500",
  },
  {
    icon: <BarChart3 size={22} />,
    title: "Performance Analytics",
    tag: "Insights",
    tagColor: "text-blue-500 bg-blue-500/10 border-blue-500/20",
    description: "Your dashboard is your command center. Track interview readiness, monitor skill proficiency across domains, view your annual activity heatmap, and get AI-generated feedback that tells you exactly what to improve.",
    highlights: [
      "Interview Readiness Score (0–100%)",
      "Skill proficiency bars per domain",
      "Annual activity heatmap (interview-only glow)",
      "AI Feedback Feed with strength & critical analysis",
      "Weekly progress streaks",
    ],
    free: "Basic analytics",
    pro: "Full analytics + weekly AI reports",
    color: "hover:border-blue-500/40",
    glow: "hover:shadow-[0_0_30px_rgba(96,165,250,0.1)]",
    iconBg: "bg-blue-500/10 text-blue-500",
  },
  {
    icon: <Radio size={22} />,
    title: "Voice Interview Mode",
    tag: "Advanced",
    tagColor: "text-rose-500 bg-rose-500/10 border-rose-500/20",
    description: "Simulate a real interview environment with full voice support. The AI asks questions aloud, you speak your answers, and the system transcribes and evaluates your response — all in real time.",
    highlights: [
      "AI speaks questions using text-to-speech",
      "Browser-based voice recognition (no install)",
      "Live waveform and speaking indicator",
      "Webcam feed for realistic interview feel",
      "Seamlessly switch between voice and chat",
    ],
    free: "Available in chat sessions",
    pro: "Full voice mode with AI auto-speak",
    color: "hover:border-rose-500/40",
    glow: "hover:shadow-[0_0_30px_rgba(251,113,133,0.1)]",
    iconBg: "bg-rose-500/10 text-rose-500",
  },
];

export const PLANS = [
  {
    name: "Free",
    price: "₹0",
    period: "forever",
    description: "Get started with the essentials",
    features: [
      "5 mock interviews per month",
      "2 CV generations per month",
      "100 AI chat credits",
      "Basic performance analytics",
      "JP-Sensei roadmap access",
      "Chat mode interviews",
    ],
    cta: "Get Started Free",
    highlight: false,
    icon: <Zap size={16} />,
  },
  {
    name: "Pro",
    price: "₹499",
    period: "/month",
    description: "Unlock your full interview potential",
    features: [
      "Unlimited mock interviews",
      "Unlimited CV generations",
      "Unlimited AI chat credits",
      "Full analytics + weekly AI reports",
      "Voice interview mode",
      "Priority AI response speed",
      "Interview history & export",
      "Priority support",
    ],
    cta: "Upgrade to Pro",
    highlight: true,
    icon: <Star size={16} />,
  },
  {
    name: "Enterprise",
    price: "₹1,999",
    period: "/month",
    description: "For teams and institutions",
    features: [
      "Everything in Pro",
      "Team management dashboard",
      "Custom job role configuration",
      "Bulk interview sessions",
      "API access",
      "Dedicated account manager",
      "Custom branding options",
      "SLA & compliance support",
    ],
    cta: "Contact Us",
    highlight: false,
    icon: <Crown size={16} />,
  },
];

export const FAQS = [
  {
    q: "Can I cancel my Pro subscription anytime?",
    a: "Yes — cancel anytime from Settings → Subscription. You'll retain Pro access until the end of your billing period.",
  },
  {
    q: "Does voice mode work on all browsers?",
    a: "Voice mode uses the Web Speech API, which works best on Chrome and Edge. Firefox has limited support.",
  },
  {
    q: "Is my CV data stored on your servers?",
    a: "No. CV input is processed and immediately deleted after generation. We never store your resume content.",
  },
  {
    q: "What AI powers the interview questions?",
    a: "We use Anthropic's Claude (claude-haiku) — one of the most capable and safe AI models available.",
  },
  {
    q: "How is the interview score calculated?",
    a: "Scores are based on technical accuracy, communication clarity, problem-solving approach, and confidence indicators.",
  },
  {
    q: "Can I use this for non-tech interviews?",
    a: "Currently the platform focuses on CSE and tech roles. Non-tech support is planned for a future update.",
  },
];

export const STATS = [
  { value: "20+", label: "Job Roles" },
  { value: "10",  label: "Questions" },
  { value: "4",   label: "JP Phases" },
  { value: "∞",   label: "Practice"  },
];